name: Node.js CI

on:
  push:
    branches: ["master"]

jobs:
  build:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [20.x]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Set environment variables
      run: |
        echo "MONGODB_URI=${{ secrets.MONGODB_URI }}" >> .env
        echo "PASSREDIS=${{ secrets.PASSREDIS }}" >> .env
        echo "HOSTREDIS=${{ secrets.HOSTREDIS }}" >> .env
        echo "PORTREDIS=${{ secrets.PORTREDIS }}" >> .env
        echo "KAFKA_BROKERS=${{ secrets.KAFKA_BROKERS }}" >> .env
        echo "JWT_SECRET=${{ secrets.JWT_SECRET }}" >> .env
        echo "PORT=${{ secrets.PORT }}" >> .env
        echo "PORT=${{ secrets.NODE_ENV }}" >> .env
        echo "PORT=${{ secrets.JWT_EXPIRES_IN }}" >> .env
    - name: Install dependencies
      run: npm ci
